### PR TITLE
MP-48336-vulnerable-java-script-dependencies

### PR DESCRIPTION
**Pull request by amin19948**
https://miceportal.atlassian.net/browse/MP-48336

### CODE REVIEW

**Review by stereosupersonic — COMMENTED** [review]
Did you do the changes on your own or did you merge some code from another repo?

**Comment by amin19948** [comment]
> Did you do the changes on your own or did you merge some code from another repo?

i did them on my own

**Comment by stereosupersonic** [comment]
ok here https://github.com/konvenit/jquery-datatables-rails/blob/165d4dff44e26b5050c05d1d31566d0883200883/app/assets/javascripts/dataTables/jquery.dataTables.js#L2 is written *SpryMedia Ltd* do you work for them?

**Comment by amin19948** [comment]
> Did you do the changes on your own or did you merge some code from another repo?

Sorry I copied it from original repo
https://github.com/DataTables/DataTables/blob/master/media/js/jquery.dataTables.js
I meant that i didn't take it from rails gem

**Review by ahmedm10 — APPROVED** [review]

**Review by stereosupersonic — APPROVED** [review]

**Pull request merged**
